language: python
python:
  - "2.6"
  - "2.7"
install:
    # Install old (pytest-)flake8 for py26
  - pip install -q 'flake8<3'
  - pip install pydocstyle
script:
 - python -c "from pocsuite.api.cannon import Cannon; import pocsuite"
 - python pocsuite.py --help
 - flake8 . --max-line-length=120 --exclude pocsuite/thirdparty --ignore F401,N802,N803,N806,E501,N813,N801,N812
